Fix GPU error messages for fuzzy deduplication
NVIDIA-NeMo/Curator pull request #387
Opened 2024-11-22 00:48 UTC by sarahyurick

- [ ] Raise a clear and readable error if the Dask client is not GPU-based
- [ ] Raise a clear and readable error if the dataset’s backend is not cuDF

2025-01-15 22:52 UTC, sarahyurick commented
cc @Maghoumi please let me know if these error messages look more how you would expect them.

2025-02-18 18:26 UTC, Maghoumi approved these changes

2025-02-18 18:26 UTC, Maghoumi commented on nemo_curator/modules/fuzzy_dedup/bucketstoedges.py
> +        if "cudf" not in str(type(dataset.df)):
Since this pattern is repeated, it might be better to move to a separate helper (e.g. `checks.py`) so it can be re-used in different places.

Something like: `ensure_cudf(dataset, module="buckets_to_edges")` which would print something like:
```
A Dask DataFrame with cuDF backend is required to run 'buckets_to_edges'. Please convert using....
```

2025-02-18 21:38 UTC, sarahyurick commented on nemo_curator/modules/fuzzy_dedup/bucketstoedges.py
> +        if "cudf" not in str(type(dataset.df)):
Thanks, I see what you mean but for now I'm not sure whether it's worth adding a new script for this. I will ask others to review as well, thank you.

2025-04-08 20:51 UTC, ayushdg requested changes
Minor nits around the explicit cudf type checks and some questions around inheriting some of these from the BaseModule

2025-04-08 20:51 UTC, ayushdg commented on nemo_curator/datasets/doc_dataset.py
> +
Does it make sense to use the `ToBackend` module here or add some of the same checks as the __init__ method from there?

cc: @ryantwolf if you have thoughts.

2025-04-08 20:51 UTC, ayushdg commented on nemo_curator/modules/fuzzy_dedup/bucketstoedges.py
>          return result_df
Alternatively this class since it follows the same `__call__` pattern can probably inherit from BaseModule?

2025-04-08 20:51 UTC, ayushdg commented on nemo_curator/modules/fuzzy_dedup/bucketstoedges.py
> +        if "cudf" not in str(type(dataset.df)):
Can call the `is_cudf_type` utility instead of the explicit check here instead.

2025-04-08 20:51 UTC, ayushdg commented on nemo_curator/modules/fuzzy_dedup/connectedcomponents.py
> +    def __call__(self, output_path):
The main reason this was not kept as the standard `__call__` method is because those typically have an assumption of `DocDataset` in `DocDataset` out. Since this doesn't follow the same pattern, it cannot be chained well in `Sequential`. Not sure if we should revert back to the old name or expand the definition of what this method can do.

2025-04-08 20:51 UTC, ayushdg commented on nemo_curator/modules/fuzzy_dedup/fuzzyduplicates.py
> +        if "cudf" not in str(type(dataset.df)):
Same comment as above

2025-04-08 20:51 UTC, ayushdg commented on nemo_curator/modules/fuzzy_dedup/fuzzyduplicates.py
> +            print(f"Stage {stage_num} (False Positive Check): Map_Buckets complete!")
Lol thanks for updating.

2025-04-08 20:51 UTC, ayushdg commented on nemo_curator/modules/fuzzy_dedup/lsh.py
> +        if "cudf" not in str(type(dataset.df)):
Since this is a public class with a `__call__` method can default to inheriting from BaseModule instead.

2025-04-08 20:51 UTC, ayushdg commented on nemo_curator/modules/fuzzy_dedup/minhash.py
> +        if "cudf" not in str(type(dataset.df)):
Same

2025-08-12 16:16 UTC, sarahyurick commented
Should not be needed after Ray refactor.

2025-08-12 16:16 UTC, closed without merging